version: "3.9"
services:

  mysql-api:
    image: mysql
    container_name: bancodedadosMysql
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: auth


  api:
    image: auth-spring
    container_name: minha-api
    ports:
      - 8082:8082
    depends_on:
      - mysql-api




